# Exported from Render on 2026-01-23T18:30:19Z
version: "1"
projects:
- name: planinarko
  environments:
  - name: Production
    services:
    - type: web
      name: planinarko-backend
      runtime: docker
      repo: https://github.com/Vito510/progi-projekt
      plan: free
      envVars:
      - key: DB_USERNAME
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: PORT
        sync: false
      - key: HOSTNAME
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      region: frankfurt
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
      rootDir: backend
